### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by limeryls** [ptimatth/GeorideHA#1]
I don't know why, I can't login to georide when I will configure it.
Whereas my credentialds are working fine in browser or app...

**Comment by ptimatth** [comment]
Hi, i will check it out later, can you share me your Home Assistant version before?

**Comment by ptimatth** [comment]
i don't have motorcycle for a while, but il look i  have the same problem since one week

**Comment by limeryls** [comment]
> Hi, i will check it out later, can you share me your Home Assistant version before?

I'm using the last versionn of HomeAssistant:
- HassOS 3.12
- HACS 0.23.2

**Comment by ptimatth** [comment]
HI have integrate your PullRequest and t seem to work for met i have removed the old integration and reopen new one.

**Comment by ptimatth** [comment]
Without response, i will close this issue for now. I wish i have solved your problem.
