### ISSUE TITLE
data updated every 10 minutes

### ISSUE THREAD

**Issue by ProBreizh** [ptimatth/GeorideHA#10]
hello,

Is it normal that my georide data is updated every 10 minutes? I have the impression that the georide 3 disconnects and reconnects 10 minutes later on home assistant. 

Is there a solution to switch to real time? 
![image_2024-01-11_213458731](https://github.com/ptimatth/GeorideHA/assets/22798348/1a1baaf9-e68b-4238-b6d1-46a6cd455589)

**Comment by ptimatth** [comment]
Hi, 
you have probably an issue with the socket connection.

The 10 minutes updates is the fallback mode. 
Can you check the log of you home assistant?

**Comment by ProBreizh35** [comment]
hi,
After checking, I only have this line to point out an error.

I have uninstalled, reinstalled, always the same thing 

"ERROR (MainThread) [custom_components.georide] Error requesting Rs3 data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"

**Comment by ptimatth** [comment]
That's weird, have you checked when your bike is moving?
We have an event when the bike is moving and when is not, we don't receive many events.
