### ISSUE TITLE
Error with jwt.decode, missing "algorithms" argument

### ISSUE THREAD

**Issue by Inervo** [ptimatth/GeorideHA#4]
Hi,

Since a recent update have modified jwt.decode function.
I now have the following issue when trying to load GeorideHA integration:

> Logger: homeassistant.config_entries
> Source: custom_components/georide/__init__.py:187
> Integration: GeoRide (documentation)
> First occurred: 16:31:49 (1 occurrences)
> Last logged: 16:31:49
> 
> Error setting up entry MyMail@gmail.com for georide
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/config/custom_components/georide/__init__.py", line 98, in async_setup_entry
>     await context.init_context(hass)
>   File "/config/custom_components/georide/__init__.py", line 247, in init_context
>     await self.force_refresh_trackers()
>   File "/config/custom_components/georide/__init__.py", line 227, in force_refresh_trackers
>     await self.get_token())
>   File "/config/custom_components/georide/__init__.py", line 187, in get_token
>     jwt_data = jwt.decode(self._token, verify=False)
>   File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 119, in decode
>     decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 86, in decode_complete
>     raise DecodeError(
> jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().

Can you have a link into this please ? :)

**Comment by ckd77** [comment]
Hi!

Same error for info since the pass of HA in 2021.10.0 and persistent in 2021.10.01;) Awaiting your correction :)
By the way, thank you for your plugins.
