### ISSUE TITLE
KeyError: 'deviceButtonAction'

### ISSUE THREAD

**Issue by Inervo** [ptimatth/GeorideHA#5]
Hi,

There seems a new update broke Georide on Home Assistant.

When restarting Home Assistant, I get this error :

> Logger: homeassistant.config_entries
> Source: custom_components/georide/__init__.py:226
> Integration: GeoRide ([documentation](https://github.com/ptimatth/GeorideHA))
> First occurred: 14:00:37 (1 occurrences)
> Last logged: 14:00:37
> 
> Error setting up entry inervo@gmail.com for georide
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/georide/__init__.py", line 98, in async_setup_entry
>     await context.init_context(hass)
>   File "/config/custom_components/georide/__init__.py", line 247, in init_context
>     await self.force_refresh_trackers()
>   File "/config/custom_components/georide/__init__.py", line 226, in force_refresh_trackers
>     new_georide_trackers = await self._hass.async_add_executor_job(GeoRideApi.get_trackers,
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.9/site-packages/georideapilib/api.py", line 122, in get_trackers
>     trackers.append(GeoRideTracker.from_json(json_tracker))
>   File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py", line 544, in from_json
>     json['deviceButtonAction'],
> KeyError: 'deviceButtonAction'
> 
> 
> 

Any way to fix this?

**Comment by ptimatth** [comment]
Hi, i haven't check but it look like an update of GeoRideAPI response from your error message, i will look at this tonight

**Comment by ptimatth** [comment]
Fixed in [0.8.2](https://github.com/ptimatth/GeorideHA/releases/tag/0.8.2)
